[package]
name = "bump_version"
version = "0.0.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "=1.0.20"
regex = "=1.10.2"
